### ISSUE TITLE
Plugin working with jquery 3.2.1?

### ISSUE THREAD

**Issue by verveuster** [bartholomej/material-scrolltop#6]
Hi
The console on chrome browser gives me an error when I click the top button:

material-scrolltop.js:46 Uncaught TypeError: $(...).animate is not a function
    at HTMLButtonElement.<anonymous> (material-scrolltop.js:46)
    at HTMLButtonElement.dispatch (jquery-3.2.1.slim.min.js:3)
    at HTMLButtonElement.q.handle (jquery-3.2.1.slim.min.js:3)

I am using bootstrap setup

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" `crossorigin="anonymous"></script>`

**Comment by verveuster** [comment]
Found out that 3.2.1 has problems with animation. Tried 3.3.1 and it works perfect.

**Comment by bartholomej** [comment]
Thanks for reporting issue @verveuster 
Does it mean there was an issue connected with jQuery? So everything is ok now? ;)

**Comment by verveuster** [comment]
Yes, the problem is solved. Thanks!

Freundliche Grüsse
Res Nägeli

--

Verve Webdesign und Grafik GmbH
Aathalstrasse 84
CH-8610 Uster
Fon +41 43 399 03 92
rnaegeli@verve.ch <info@verve.ch>
www.verve.ch

2018-01-31 10:38 GMT+01:00 BART! <notifications@github.com>:
